services:
  nginx:
    container_name: nginx
    image: nginx:1.27.0-bookworm-perl
    # restart: always
    networks:
      - webserver
    ports:
      - 80:80    
      - 443:443
    volumes:
      - ./_Volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./_Volumes/certbot/www/:/var/www/certbot/:ro
      - ./_Volumes/certbot/conf/:/etc/ssl/certs/conf/:ro

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    networks:
      - webserver
    volumes:
      - ./_Volumes/certbot/www/:/var/www/certbot/:rw
      - ./_Volumes/certbot/conf/:/etc/letsencrypt/:rw

  mysql:
    container_name: mysql
    image: mariadb:10.6.4-focal
    # For MySQL, uncomment the next line and comment the one before
    #image: mysql:8.0.27x
    command: '--default-authentication-plugin=mysql_native_password'
    # restart: always
    networks:
      - webserver
    expose:
      - 3306
      - 33060
    volumes:
      - ./_Volumes/mysql:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    environment:
      MYSQL_ROOT_PASSWORD: /run/lib/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: /run/lib/db_password

  wordpress:
    container_name: wordpress
    image: wordpress:latest
    # restart: always
    networks:
      - webserver
    depends_on:
      - mysql
    expose:
      - 80
    volumes:
      - ./_Volumes/wordpress:/var/www/html          
    secrets:
      - db_password
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: /run/lib/db_password

secrets:
   db_password:
     file: ./.secrets/db_password.txt
   db_root_password:
     file: ./.secrets/db_root_password.txt

networks:
  webserver:
    name: webserver    


